### ISSUE TITLE
Deployment fails on build #9

### ISSUE THREAD

**Issue by penguinairlines** [penguinairlines/learn-kubernetes-multidocker#2]
After making changes to match Steve's code, the build has broken. Travis now fails with the following error:
```
 FAIL  src/App.test.js
  ● Test suite failed to run
    Cannot find module '@testing-library/jest-dom/extend-expect' from 'setupTests.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/setupTests.js:5:1)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.847s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
The command "docker run -e CI=true [secure]/react-test npm test" exited with 1.
```

**Comment by penguinairlines** [comment]
fixed. Commit #9 was the fault.
